name: workflow
on:
  push:
    branches: [master]
    paths:
      - 'dist/*.json'
      - '!**.js'
  pull_request:


env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
jobs:
  update_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: 'pnpm'
      - name: Install npm packages
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
          pnpm install
      - name: Build
        run: |
          pnpm run check
          pnpm run build
      - name: Build documentation
        run: pnpm run docs:publish
      - name: Deploy to Github Pages
        if: ${{ github.event_name == 'push' && success() && github.actor == 'machsix'}}
        uses:  crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
          keep_history: true
          commit_message: ${{ format('Commit sha {0}', github.sha)}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
